language: perl
sudo: false

addons:
  postgresql: "9.3"

perl:
  - "5.14"
  # - "5.16"
  # - "5.18"
  # - "5.20"
  # - "blead"

env:
  - "PG_PORT=5432 HARNESS_PERL_SWITCHES='-MDevel::Cover=+ignore,local,^t/'"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
  allow_failures:
    - perl: "blead"

branches:
  except:
    - releases

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing

after_success:
  - coverage-report

notifications:
  email:
    recipients:
      - sedlakmichal@gmail.com
    on_success: change
    on_failure: always
