---
abstract: 'PMLTQ command line interface'
author:
  - 'Matyáš Kopp <matyas.kopp@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0'
  Test::Most: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PMLTQ-Commands
no_index: {}
provides:
  PMLTQ::Base:
    file: lib/PMLTQ/Base.pm
    version: v2.0.2
  PMLTQ::Command:
    file: lib/PMLTQ/Command.pm
    version: v2.0.2
  PMLTQ::Command::configuration:
    file: lib/PMLTQ/Command/configuration.pm
    version: v2.0.2
  PMLTQ::Command::convert:
    file: lib/PMLTQ/Command/convert.pm
    version: v2.0.2
  PMLTQ::Command::delete:
    file: lib/PMLTQ/Command/delete.pm
    version: v2.0.2
  PMLTQ::Command::init:
    file: lib/PMLTQ/Command/init.pm
    version: v2.0.2
  PMLTQ::Command::initdb:
    file: lib/PMLTQ/Command/initdb.pm
    version: v2.0.2
  PMLTQ::Command::load:
    file: lib/PMLTQ/Command/load.pm
    version: v2.0.2
  PMLTQ::Command::query:
    file: lib/PMLTQ/Command/query.pm
    version: v2.0.2
  PMLTQ::Command::verify:
    file: lib/PMLTQ/Command/verify.pm
    version: v2.0.2
  PMLTQ::Command::version:
    file: lib/PMLTQ/Command/version.pm
    version: v2.0.2
  PMLTQ::Command::webdelete:
    file: lib/PMLTQ/Command/webdelete.pm
    version: v2.0.2
  PMLTQ::Command::webload:
    file: lib/PMLTQ/Command/webload.pm
    version: v2.0.2
  PMLTQ::Command::webtreebank:
    file: lib/PMLTQ/Command/webtreebank.pm
    version: v2.0.2
  PMLTQ::Command::webverify:
    file: lib/PMLTQ/Command/webverify.pm
    version: v2.0.2
  PMLTQ::Commands:
    file: lib/PMLTQ/Commands.pm
    version: v2.0.2
requires:
  Hash::Merge: '0'
  JSON: '0'
  PMLTQ: v2.0.1
  URI::Encode: '0'
resources:
  bugtracker: https://github.com/ufal/pmltq-commands/issues
  homepage: http://ufal.mff.cuni.cz/pmltq/
  repository: https://github.com/ufal/pmltq-commands.git
version: 2.0.2
x_authority: cpan:MATY
x_authority_from_module: PMLTQ::Commands
x_permissions_from_module: PMLTQ::Commands
x_serialization_backend: 'YAML::Tiny version 1.70'
